// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xskfpoexkcmbukxguhaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhza2Zwb2V4a2NtYnVreGd1aGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MTM0ODcsImV4cCI6MjA1NTQ4OTQ4N30.VvxjJtBsc8rOYGgAR5yHclWYWBYYgnX_Cgi9V_k9QJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);